# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Plantastic
email: martha.kandziora@yah...com
description: >- # this means to ignore newlines until "baseurl:"
 Plantastic is a site about plant research in general and science I find particularly interesting.
baseurl: "/plantastic" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  mkandziora

owner:
  name:  Martha Kandziora
  
  email:  martha.kandziora@yah...com

# Build settings
markdown: kramdown

navigation:
#  - title: Home
#    url: /home  
#    xternal: 0
 
  - title: Research Interests
    url: /research_interest  
    xternal: 0  
  - title: Projects
    url: /research
    xternal: 0
 
  - title: Plantmap
    url: https://mkandziora.github.io/plantmap/
    xternal: 1
  - title: Blog
    url: /blog
  - title: Teaching
    url: /teaching
  - title: Publications
    url: /publications
    xternal: 0  
  # - title: About
  #   url: /about
  #   xternal: 0
  # - title: CV
  #   url: /cv
    xternal: 0
#  - title: About
#    url: /about  
#    xternal: 0
  
#  - title: Github
#    url: https://github.com/mkandziora         

#remote_theme: brianmaierjr/long-haul
#plugins:
#  - jekyll-feed
#plugins:
#  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
